tools,watchfrr: coordinate timeout when restarting a daemon
When watchfrr restarts a hung or failed daemon, convey the
timeout that it's going to use to the shell script that's
actually doing the work. If the two timeouts are different,
watchfrr may terminate the shell script prematurely.

Also add a "kill" step to frrcommon's daemon_stop(): if
a daemon is hung or deadlocked, it may not be able to react
to SIGINT, and SIGKILL may be necessary.

Signed-off-by: Mark Stapp <mstapp@nvidia.com>

diff --git a/tools/frrcommon.sh.in b/tools/frrcommon.sh.in
--- a/tools/frrcommon.sh.in
+++ b/tools/frrcommon.sh.in
@@ -212,13 +212,38 @@ daemon_stop() {
 		return 1
 	fi
 
-	debug "kill -2 $pid"
-	kill -2 "$pid"
 	cnt=1200
+
+	#
+	# Allow calling program to convey the timeout it may be using
+	#
+	if [ -n "$FRR_WATCHFRR_TIMEOUT" ] ; then
+		$(( cnt = "$FRR_WATCHFRR_TIMEOUT" - 5 ))
+		$(( cnt *= 10 ))
+	fi
+
+	debug "kill -2 $pid, cnt $cnt"
+	kill -2 "$pid"
+
 	while kill -0 "$pid" 2>/dev/null; do
 		sleep .1
 		[ $(( cnt -= 1 )) -gt 0 ] || break
 	done
+
+	if kill -0 "$pid" 2>/dev/null; then
+		debug "kill -9 $dmninst, pid $pid"
+		log_success_msg "Failed to stop $dmninst, killing pid $pid ..."
+
+		kill -9 "$pid"
+
+		# And wait a bit for the kill to take effect
+		cnt=5
+		while kill -0 "$pid" 2>/dev/null; do
+			sleep .1
+			[ $(( cnt -= 1 )) -gt 0 ] || break
+		done
+	fi
+
 	if kill -0 "$pid" 2>/dev/null; then
 		[ "$2" = "--quiet" ] || log_failure_msg "Failed to stop $dmninst, pid $pid still running"
 		still_running=1
